### ISSUE TITLE
Crash in isAvailable

### ISSUE THREAD

**Issue by arj03** [dominictarr/epidemic-broadcast-trees#14]
I was running 6.0.1 and hit the following crasher bug. Not sure if this is still a bug in latest version.

/home/chrx/.ssb/node_modules/ssb-ebt/node_modules/epidemic-broadcast-trees/events.js:34
      if((peer.clock[feed_id] || 0) > (state.clock[feed_id] || 0)) {
                    ^

TypeError: Cannot read property '@6CAxOI3f+LUOVrbAl0IemqiS7ATpQvr9Mdw9LC4+Uv0=.ed25519' of null
    at isAvailable (/home/chrx/.ssb/node_modules/ssb-ebt/node_modules/epidemic-broadcast-trees/events.js:34:21)
    at Object.exports.timeout (/home/chrx/.ssb/node_modules/ssb-ebt/node_modules/epidemic-broadcast-trees/events.js:351:22)
    at Timeout._onTimeout (/home/chrx/.ssb/node_modules/ssb-ebt/node_modules/epidemic-broadcast-trees/index.js:87:25)
    at ontimeout (timers.js:478:11)
    at Timer.unrefdHandle (timers.js:598:5)

**Comment by dominictarr** [comment]
hmm, yes I think this could happen if it considers switching the active subscriptions before the peeClock has loaded.

I made a test an reproduced this, fixed in 6.1.2!

**Comment by arj03** [comment]
Thanks!
