### ISSUE TITLE
Crash replicating

### ISSUE THREAD

**Issue by arj03** [dominictarr/epidemic-broadcast-trees#15]
/home/chrx/dev/scuttlebot/node_modules/epidemic-broadcast-trees/events.js:415
      if(peer.clock[feed_id] || 0 > state.clock[feed_id] || 0) {
                   ^
TypeError: Cannot read property '@f/6sQ6d2CMxRUhLpspgGIulDxDCwYD7DzFzPNr7u5AU=.ed25519' of null
    at /home/chrx/dev/scuttlebot/node_modules/epidemic-broadcast-trees/events.js:415:20
    at eachFrom (/home/chrx/dev/scuttlebot/node_modules/epidemic-broadcast-trees/events.js:75:8)
    at Object.exports.timeout (/home/chrx/dev/scuttlebot/node_modules/epidemic-broadcast-trees/events.js:413:5)
    at Timeout._onTimeout (/home/chrx/dev/scuttlebot/node_modules/epidemic-broadcast-trees/index.js:94:25)
    at ontimeout (timers.js:478:11)
    at Timer.unrefdHandle (timers.js:598:5)

**Comment by dominictarr** [comment]
it looks like it's hit the timeout before the clock has loaded... (which could happen) but that someone requested an invalid feed id worries me more.

**Comment by dominictarr** [comment]
should be fixed in 6.2.2

**Comment by dominictarr** [comment]
also i added better validation so if weird feed ids happen they will be ignored. which is fixed in ssb-ebt@5.1.5

**Comment by arj03** [comment]
I didn't remove anything, that was the error I got. I think I only saw it once and then restarted and didn't see it again, just wanted to report it as its a crasher. Thanks for fixing!
