### ISSUE TITLE
Crash in canSend

### ISSUE THREAD

**Issue by qypea** [dominictarr/epidemic-broadcast-trees#17]
Yesterday my ssb pub was crashing repeatedly, with the following error. I poked around a little trying to figure out the root cause and settled on checking if `state` was valid in this function. Not sure if that's the preferred solution but it did stop the crash and get my pub running better again. Let me know if there's anything I can do to help

```
/home/pi/easy-ssb-pub/node_modules/epidemic-broadcast-trees/stream.js:84
      state.msgs.length || state.notes
           ^
TypeError: Cannot read property 'msgs' of undefined
    at EBTStream.canSend (/home/pi/easy-ssb-pub/node_modules/epidemic-broadcast-
    at EBTStream.resume (/home/pi/easy-ssb-pub/node_modules/epidemic-broadcast-t
    at Object.update (/home/pi/easy-ssb-pub/node_modules/epidemic-broadcast-tree
    at Timeout._onTimeout (/home/pi/easy-ssb-pub/node_modules/epidemic-broadcast
    at ontimeout (timers.js:365:14)
    at Timer.unrefdHandle (timers.js:466:3)
```

**Comment by qypea** [comment]
Initial results with 6.3.4 https://github.com/dominictarr/epidemic-broadcast-trees/commit/4389256fe39e421959b0ba4a8da44ef2e7f9b183 look good. Thanks for chasing this one down
