### ISSUE TITLE
write after ebt stream ended

### ISSUE THREAD

**Issue by qypea** [dominictarr/epidemic-broadcast-trees#19]
Running 6.3.4 I am now getting the following crash in my logs every few minutes when the pub starts syncing data. Not sure what would be causing this. The remote printed below is another pub if that helps chase it down.

```
 /home/pi/easy-ssb-pub/node_modules/epidemic-broadcast-trees/stream.js:40
  if(this.ended) throw new Error('write after ebt stream ended:'+this.remote)
                  ^
 Error: write after ebt stream ended:@XgC5wDA2EW++ufaDrjRDHXA7Dyd1ce5bTenCm2u6PZU=.ed25519
     at EBTStream.write (/home/pi/easy-ssb-pub/node_modules/epidemic-broadcast-trees/stream.js:40:24)
     at next (/home/pi/easy-ssb-pub/node_modules/push-stream-to-pull-stream/sink.js:31:21)
     at PacketStreamSubstream.weird.read (/home/pi/easy-ssb-pub/node_modules/muxrpc/pull-weird.js:33:7)
     at PacketStream._onstream (/home/pi/easy-ssb-pub/node_modules/packet-stream/index.js:204:12)
     at PacketStream.write (/home/pi/easy-ssb-pub/node_modules/packet-stream/index.js:135:41)
     at /home/pi/easy-ssb-pub/node_modules/muxrpc/pull-weird.js:56:15
     at /home/pi/easy-ssb-pub/node_modules/pull-stream/sinks/drain.js:24:37
     at /home/pi/easy-ssb-pub/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
     at Object.cb (/home/pi/easy-ssb-pub/node_modules/packet-stream-codec/index.js:111:11)
     at drain (/home/pi/easy-ssb-pub/node_modules/pull-reader/index.js:39:14)
```

**Comment by cryptix** [comment]
I'm gettig the same on a newly installed pub using sbot@11.4.2

**Comment by dominictarr** [comment]
great, okay this must have been caused by: https://github.com/dominictarr/epidemic-broadcast-trees/pull/18 (if someone connects who is blocked, disconnect them)

**Comment by qypea** [comment]
Did a little digging and it seems to be a problem with the state tracking between ssb-ebt and this code. It seems to me like when this code ends the connection ssb-ebt doesn't notice, continues trying to use the connection, calls write, and triggers the error. 

Here's a workaround patch that seems to get things working again for me. My intent was to make this layer not close the connection itself; rather let the upper layer deal with that and survive the intervening time.

```
diff --git a/stream.js b/stream.js
index f4646ef..2e975dc 100644
--- a/stream.js
+++ b/stream.js
@@ -79,12 +79,12 @@ EBTStream.prototype.abort = EBTStream.prototype.end = function (err) {
 EBTStream.prototype.canSend = function () {
   var state = this.peer.state.peers[this.remote]
   return (
+    state &&
+    !state.blocked &&
     this.sink &&
     !this.sink.paused &&
     !this.ended && (
-      //missing state means this peer was blocked,
-      //end immediately.
-      state.blocked || state.msgs.length || state.notes
+      state.msgs.length || state.notes
     )
   )
 }
@@ -93,9 +93,7 @@ EBTStream.prototype.resume = function () {
   var state = this.peer.state.peers[this.remote]
   if(!this.sink || this.sink.paused) return
   while(this.canSend()) {
-    if(state.blocked)
-      this.end()
-    else if(state.msgs.length) {
+    if(state.msgs.length) {
       if(this.peer.logging) console.error("EBT:send", JSON.stringify(state.msgs[0], null, 2))
       this.sink.write(state.msgs.shift())
     }
```

**Comment by dominictarr** [comment]
I think the problem was actually in push-stream-to-pull-stream, if you update that to 1.0.3 (reinstall and you'll get it) and i think it should start working again.

**Comment by qypea** [comment]
Updating seems to fix this issue, but introduces another. Unfortunately this means I can't run this fix for long term stability testing until the other issue is fixed. It does appear better though so I'll close this issue for now.
